services:
  - type: web
    name: simpeg-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --no-interaction --no-plugins --no-scripts --prefer-dist
      php artisan config:clear
      php artisan route:clear
      php artisan view:clear
      npm install
      npm run build
      php artisan storage:link
    startCommand: php artisan migrate --force && heroku-php-apache2 public/
    envVars:
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: "SIYANTI BKPSDM"

  - type: worker
    name: simpeg-worker
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --no-interaction --no-plugins --no-scripts --prefer-dist
      php artisan config:clear
    startCommand: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: vvhf14.h.filess.io
      - key: DB_PORT
        sync: 61002
      - key: DB_DATABASE
        sync: dbsimpeg_postnearon
      - key: DB_USERNAME
        sync: dbsimpeg_postnearon
      - key: DB_PASSWORD
        sync: 8fe89d169fbf06a4d6aa46e9c080f4e4dcc98427
      - key: APP_KEY
        sync: false
      - key: MAIL_MAILER
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        sync: false
